Skip iteration over untagged images
Having untagged images present causes a failure
with an `undefined method `first' for nil:NilClass (NoMethodError)`
error message.